### ISSUE TITLE
Clarify format of jmh.edn file

### ISSUE THREAD

**Issue by glts** [jgpc42/lein-jmh#3]
The file extension of the `jmh.edn` file would point to it being edn,
but it doesn’t seem to be edn. For example, the sample file is clearly
not valid edn, as it has an anonymous function literal and a symbol that
resolves to a static method of a Java class (`Thread/sleep`).
[edn](https://github.com/edn-format/edn) is a data format that isn’t
tied to a particular language (I’m sure you know this).

As far as I understand, currently `jmh.edn` may contain arbitrary
Clojure code but must evaluate to a map. I’m not sure if the file should
be called `jmh.edn` then; certain expectations come with the extension:
purely declarative, no Clojure constructs.

Me, I would welcome a pure edn benchmark file.

Possible changes: call the default file `jmh.clj`; actually make it an
edn file (perhaps with the proviso that unqualified symbols will be in
`clojure.core`); document clearly what the contents of the file may or
may not be.

**Comment by jgpc42** [comment]
Yes, you are right of course. Actually, the jmh-clojure [sample file](https://github.com/jgpc42/jmh-clojure/blob/master/resources/sample.jmh.edn) *is* valid edn. But more on this in a second. 

I mentioned before in #1 that I was originally using `edn/read-string`. Since `fn` lists were already allowed, I switched to `read-string` because I thought users would likely try to use the anonymous function literal reader macro `#(...)`, and would be later confused when the edn reader threw `RuntimeException No dispatch macro for: (` at them. 

I'm definitely against changing the file name to `jmh.clj` - then having to explain why `def` doesn't work as expected. Switching back to proper edn is the way to go.

The question seems to be whether to disallow *valid* edn data that is later `eval`uated. More specifically, does allowing lists that represent `fn` expressions for convenience go against the expectations/spirit of the data format? Nothing is preventing users from only using fully-qualified var symbols if they choose. I'd like to hear any thoughts you may have on this.

I personally think that bare symbol interpretation is fair game, however.

I'll think a bit more on this for the time being. Thanks for bringing this up!

**Comment by jgpc42** [comment]
Forgot to close this. To reiterate, I agree with you that proper `edn` format is the way to go, and will be required from now on. 

Also, I think the convenience of fn expression sequences (like `(partial into [])`) outweigh any phantom "bad practice" issues.
