### ISSUE TITLE
Variance?

### ISSUE THREAD

**Issue by saulshanabrook** [jgpc42/lein-jmh#5]
Is it possible to print the (sample) variance for a benchmark? I am trying to compute a confidence interval for the ratio of the means of two experiments based on the ["Rigorous Benchmarking in Reasonable Time" paper](https://kar.kent.ac.uk/33611/7/paper.pdf).

**Comment by jgpc42** [comment]
I have run into similar reporting deficiencies before with JMH output formats.

JMH supports four formats by default: `XSV`, `JSON`, `LaTeX`, and `Text`. Currently, `jmh-clojure` parses the `XSV` format to collect the data that this plugin consumes. For some strange reason, all these formats omit data that *is* reported via the raw-text status log. For example, the stack profiler has a similar [issue](https://github.com/jgpc42/jmh-clojure/wiki/JMH-Profilers).

Anyway, if we enable the `:status` option:

```bash
lein jmh '{:mode :throughput, :status true}'
```

... when the each benchmark is complete, you'll find additional statistical information at the bottom of the log:

```
...

Result "pkg.your.Benchmark.method":
  124351844.053 ±(99.9%) 1961436.954 ops/s [Average]
  (min, avg, max) = (88790768.817, 124351844.053, 131467382.315), stdev = 8304846.883
  CI (99.9%): [122390407.099, 126313281.008] (assumes normal distribution)

...
```

It's somewhat silly, but as it stands right now, you would need to manually parse the `stdev = 8304846.883` from that output, and square it to get the sample variance. No, I'm not joking. I have read the JMH sources pretty extensively, and I don't think I have missed anything. 

Additionally, I have seen some people [state](http://daniel.mitterdorfer.name/talks/2014/jmh-microbenchmarking-munich/#/19) that the `:score-error` is in some way representative of the variance. One of the authors of JMH [explains](https://stackoverflow.com/a/24725075/5829079) that it *"is a half of confidence interval"*. I'm not a statistics expert, but I don't think that is useful in your case.

My first thought on addressing this problem was to implement a custom (like `edn`) [`ResultFormat`](http://hg.openjdk.java.net/code-tools/jmh/file/fbe1b55eadf8/jmh-core/src/main/java/org/openjdk/jmh/results/format/ResultFormat.java#l31). But JMH (strangely) doesn't support them, as [`getResultFormat`](http://hg.openjdk.java.net/code-tools/jmh/file/fbe1b55eadf8/jmh-core/src/main/java/org/openjdk/jmh/runner/options/Options.java#l60) must return one of the default [types](http://hg.openjdk.java.net/code-tools/jmh/file/fbe1b55eadf8/jmh-core/src/main/java/org/openjdk/jmh/results/format/ResultFormatType.java#l27).

Seemingly, the solution to this problem is to parse the `JSON` format instead. It is the only format that [emits](http://hg.openjdk.java.net/code-tools/jmh/file/fbe1b55eadf8/jmh-core/src/main/java/org/openjdk/jmh/results/format/JSONResultFormat.java#l158) the [raw data](http://hg.openjdk.java.net/code-tools/jmh/file/fbe1b55eadf8/jmh-core/src/main/java/org/openjdk/jmh/util/ListStatistics.java#l156) needed to [calculate](http://hg.openjdk.java.net/code-tools/jmh/file/fbe1b55eadf8/jmh-core/src/main/java/org/openjdk/jmh/util/ListStatistics.java#l161) the variance. I would then need to adorn the result maps with the stats data.

I apologize for the length of this post. It is mostly a brain-dump of sorts of subsequent work to be done.

**Comment by jgpc42** [comment]
I somehow neglected to notice that if you are using the Java API directly, which `jmh-clojure` does, the [`Runner`](http://hg.openjdk.java.net/code-tools/jmh/file/fbe1b55eadf8/jmh-core/src/main/java/org/openjdk/jmh/runner/Runner.java#l179) actually returns the result data I need - I don't need to mess with result formats at all!

I should be releasing the next version of `lein-jmh` soon which will provide this statistical data in an easily accessible way.

Thanks for opening this issue! I'll leave this open until this is implemented.

**Comment by saulshanabrook** [comment]
@jgpc42 Thank you for the super thorough overview!

That's great news. Let me know if you want any help with the release.

**Comment by jgpc42** [comment]
I have updated the plugin to version [`0.2.5`](https://github.com/jgpc42/lein-jmh/blob/master/CHANGELOG.md#025-2017-12-29). It now uses `jmh-clojure` [`0.2.1`](https://github.com/jgpc42/jmh-clojure/blob/master/CHANGELOG.md#021-2017-12-29). For example, now you can do:

```bash
$ lein jmh '{:format :table, :mode :throughput, :only [:score :statistics]}'
```

... which yields (for some random test benchmark I made):

```clojure
:score               :statistics
-------------------  ------------------------------------------------------
10794610.561  ops/s  {:min 9447017.523 :max 11058052.730 :stdev 244986.485}
```

I decided not to show everything with the tabular format due to width-concerns. All data (including the `:variance`) is present with the other formats. There is also a new key: `:score-confidence`, shown here:

```bash
$ lein jmh '{:format :pprint, :mode :throughput, :only [:score :score-confidence :statistics], :status true}'
```

... which yields:

```clojure
({:score [9395765.446748171 "ops/s"],
  :score-confidence [9174881.891087499 9616649.002408843],
  :statistics
  {:max 1.1017567955323316E7,
   :mean 9395765.446748171,
   :min 6022915.115595741,
   :n 200,
   :percentiles
   {0.0 6022915.115595741,
    50.0 9358916.585551457,
    90 1.0882382672474792E7,
    95 1.0938664624879915E7,
    99 1.0991149274617761E7,
    99.9 1.1017567955323316E7,
    99.99 1.1017567955323316E7,
    99.999 1.1017567955323316E7,
    99.9999 1.1017567955323316E7,
    100 1.1017567955323316E7},
   :stdev 935234.8056497932,
   :sum 1.8791530893496342E9,
   :variance 8.746641416988065E11}})
```

I toggled `:status` above to demonstrate the numbers are consistent with the JMH log:

```
Result "pkg.some.random.bench":
  9395765.447 ±(99.9%) 220883.556 ops/s [Average]
  (min, avg, max) = (6022915.116, 9395765.447, 11017567.955), stdev = 935234.806
  CI (99.9%): [9174881.891, 9616649.002] (assumes normal distribution)
```

You can see that, for example, `:score-confidence` is just the same confidence interval data displayed above following `CI (99.9):` in the status log.

By the way, if it's useful to you, the [raw data](http://hg.openjdk.java.net/code-tools/jmh/file/fbe1b55eadf8/jmh-core/src/main/java/org/openjdk/jmh/util/Statistics.java#l148) points are also provided as `jmh/raw-data` metadata on the `:statistics` maps. You'd need to use `jmh-clojure` itself instead of the plugin to access it, obviously.

Anyway, thanks again @saulshanabrook for opening this issue. This is really nice to have. I also increased performance and simplified the code by not having to parse any output. A win-win. 👍
