### ISSUE TITLE
Better support for tools.cli

### ISSUE THREAD

**Issue by bsless** [jgpc42/lein-jmh#6]
Using JMH in a managed manner with CLI tools has more friction than using the lein plugin.
Would [supporting a tool API](https://clojure.org/reference/deps_and_cli#_best_practices_for_tool_authors) help with that?

I would not mind working on it if you're interested

Thanks

**Comment by jgpc42** [comment]
> Would supporting a tool API help with that?

I think so, and `jmh-clojure` already works perfectly fine [without Leiningen](https://github.com/jgpc42/jmh-clojure/wiki/Clojure-1.9-CLI).

Coincidentally, I've recently moved most of my workflow to Clojure tools and I already had plans to make the [task library](https://github.com/jgpc42/lein-jmh/tree/master/task#what-is-it) properly available via the tool API. All that needs to be done is to extract it from here into its own repository (since I think having "lein" in the title could be confusing) and add a few minor changes. (This wont really affect `lein-jmh` as it is already just a simple consumer of the task lib.) I'm not sure if there is an idiomatic naming scheme for these things yet, but It'll likely be called `tools.jmh`, or similar. 

I'm still working out a few details, but I had planned on doing this restructuring in the next couple of weeks. Your offer to help is very much appreciated, however. 

Anyway, I'll give you a ping from the new repo once the migration is done and we can go from there.

Thanks.

**Comment by bsless** [comment]
Glad to hear.
For reference, here's how I approached it without using jmh as a tool
https://github.com/metosin/malli/pull/525

**Comment by jgpc42** [comment]
I took a quick look at the docs, again, and it states under [*Tool installation and invocation*](https://clojure.org/reference/deps_and_cli#tool_install):

> The Clojure CLI supports the idea of running tools, which are programs that don’t use the project classpath, ...

This would seem to rule out using `jmh-clojure` as a tool because it needs to run within the classpath of the code that it is benchmarking, as it uses reflection to dynamically emit the required JMH `.class` files, and that code will also need to be available to the JMH runner subprocesses.

Please let me know if I'm missing something. Thanks.

**Comment by bsless** [comment]
I don't think you're missing anything, but that I'm taking a slightly different approach.
If I understand correctly how lein-jmh works, it lets you create a slightly more contained running environment for your code.
You want to control your class path and JVM arguments.
By adding a preparatory phase with tools.build, you can build an uberjar which contains all the dependencies you need for the test.
Once you got an uberjar, do you even need a project to run in? Your class path is just a classes dir and the uberjar.
Not even sure if it's a sensible idea. What do you think?

**Comment by jgpc42** [comment]
> If I understand correctly how lein-jmh works, it lets you create a slightly more contained running environment for your code.
You want to control your class path and JVM arguments.

Tools like Leiningen and `tools.deps` allow you to manage a `java` process that is started to execute your code. So, in `lein-jmh`'s case, all it basically does is add the additional dependency of `jmh-clojure/task` to the project classpath and execute [`jmh.task/main`][main] inside this child process, which in turn delegates to `jmh-clojure`. The core lib allows you to further manage the isolated *JMH* child processes that eventually get executed after compilation that do the actual benchmarking.

> By adding a preparatory phase with tools.build, you can build an uberjar which contains all the dependencies you need for the test.
> Once you got an uberjar, do you even need a project to run in? Your class path is just a classes dir and the uberjar.

Correct; no project will be necessary at this point, but normally the extra step of creating a jar should not be needed unless you intend to run benchmarks on a different machine than your development one and want to package everything up so you don't have to re-create the project build environment. Invoking [`jmh.core/run`][run] with or without an uberjar won't affect how the benchmarks are compiled or run.

> Not even sure if it's a sensible idea. What do you think?

That being said, creating an uberjar is a [completely valid][uberjar] way to run jmh-clojure since it runs within the jar's classpath. So if it fits your workflow, go right ahead. :)

---

As for the original issue; it seems clear that running an uberjar and cli tool support are orthogonal concerns. Maybe in the future, the cli will support an easier way of adding aliases to the current project's `deps.edn`. Until then, creating an jar or simply using an alias seems like the correct approach for now.

I hope I answered all your questions.

[main]: https://github.com/jgpc42/lein-jmh/blob/87ad9d5/task/src/jmh/main.clj#L10
[run]: https://jgpc42.github.io/jmh-clojure/doc/jmh.core.html#var-run
[uberjar]: https://github.com/jgpc42/lein-jmh/tree/84b0350/task#example

**Comment by bsless** [comment]
> Invoking [`jmh.core/run`](https://jgpc42.github.io/jmh-clojure/doc/jmh.core.html#var-run) with or without an uberjar won't affect how the benchmarks are compiled or run.

I think this hits the nail on the head regarding where my misunderstanding was - it makes no difference regarding the results or how the child process is run if the classes are loaded from clj files or from an uberjar.

It also means I can skip the preparatory phase of creating an uberjar and still get correct results by running the task (with `-X`?) in the project.

**Comment by jgpc42** [comment]
> It also means I can skip the preparatory phase of creating an uberjar and still get correct results by running the task (with -X?) in the project.

Yes, `-X` will be the recommended way to run. I've created [a new repo](https://github.com/jgpc42/jmh-clojure-task) for the task lib that will contain updated code and instructions for `clj` in the next day or so.

**Comment by jgpc42** [comment]
Just pushed `0.1.1` to Clojars. [Here's the new repo](https://github.com/jgpc42/jmh-clojure-task). If you have any problems with the enhanced `clj` support, please open an issue there.

Thanks again.
